######################################################################
# Automatically generated by qmake (2.00a) lun 4. sep 12:15:29 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Dialog.h
SOURCES += Dialog.cpp main.cpp


# Translations
TRANSLATIONS = dialog_es_ES.ts \
	dialog_fr.ts \
	dialog_de.ts
